### ISSUE TITLE
Error by installing intergration

### ISSUE THREAD

**Issue by marcel-1984** [heyajohnny/afvalinfo#439] opened 2024-05-23 20:27 UTC
I delete the hole Afval info in HACS en everywhere.
I restart the hole system and install it back fromm HACS. Then when i instaale the intergration in Devices then i get the next error: Config-flow kon niet geladen worden: {"message":"Invalid handler specified"}

**Comment by marcel-1984** [comment] 2024-05-23 20:48
This shows up in the logbook:

Logger: homeassistant.config_entries
Source: config_entries.py:2087
First occurred: 22:09:15 (9 occurrences)
Last logged: 22:44:04

Error occurred loading flow for integration afvalinfo: cannot import name 'ConfigFlowResult' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)

**Comment by heyajohnny** [comment] 2024-05-25 17:58
Can you give me some more info?
What version of Home Assistant are you using?
What language is your Home Assistant set to?
Did it work before?

**Comment by marcel-1984** [comment] 2024-05-25 18:34
Hey. 
I use 2024.1.3
11.4 and my system is in Dutch. I used it for al long time and worked perfect till last week. 

Now I can't install it anymore. Now I use afvalbeheer

**Comment by heyajohnny** [comment] 2024-05-30 10:24
I'm sorry,
I can't seem to reproduce it in my current version when setting the language to Dutch.
I assume you already followed the [Upgrade procedure](https://github.com/heyajohnny/afvalinfo?tab=readme-ov-file#breaking-changes-for-upgrading-from-v1xx-to-v2xx) if you've upgraded from version 1.x.x to the current version?
Maybe updating your Home Assistant to the latest version fixes things.
Other than that, I have no clue what it could be...

**Comment by dortatdtdx** [comment] 2024-06-03 08:44
Hey marcel-1984,
I'm facing a similar problem (no upgrade). I followed the installation approach mentioned on https://github.com/heyajohnny/afvalinfo. However, I get the same error as the original poster and did not reacht the form to fill in the address details.

== LOG ==
2024-06-03 10:25:29.570 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration afvalinfo: cannot import name 'ConfigFlowResult' from 'homeassistant.config_entries' (/opt/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py)
==

What I noticed that the file config_entries.py does contain ConfigFlow but does not contain a reference to ConfigFlowResult. Perhaps this could shed some light?

A fresh install of Afvalinfo from github version v2.1.0
Home Assistant - core 2024.3.3
Home Assistant - frontend 20240307.0
Languages both dutch / english tested.

**Comment by heyajohnny** [comment] 2024-06-03 14:37
I've removed some type checking code that used ConfigFlowResult as a type. It seems to be sort of removed from Home Assistant, but I'm not really sure and can't find any documentation about it.
Hopefully it's fixed now (in afvalinfo v2.1.1) 

@marcel-1984 @dortatdtdx Can you please let me know if it fixes the issue?

**Comment by marcel-1984** [comment] 2024-06-03 16:57
@heyajohnny Thanks for your support. Now its work again. Super Nice 👍

**Comment by dortatdtdx** [comment] 2024-06-04 07:12
Indeed it is working now! Thank you for your prompt response.

**Comment by heyajohnny** [comment] 2024-06-04 08:30
A double confirmation that it's working again. Thnx!

It's really strange that these things just pop up at some users and other users have no problem at all. When I was editing the code I could see that the ConfigFlowResult wasn't in the config_entries anymore, but it didn't get any errors in my environment.

I'm glad it's fixed, but it's really frustrating that the Home Assistant documentation is so bad...

Thanks for reporting the issue! I'm closing it now.

**Closed by heyajohnny** 2024-06-04 08:30 UTC
