### ISSUE TITLE
sensor.afvalinfo_gft not updating anymore.

### ISSUE THREAD

**Issue by JBakers** [heyajohnny/afvalinfo#251] opened 2022-01-23 15:44 UTC
gft sensor not updating:

sensor.afvalinfo_gft generates the following info: 

```
year_month_day_date: null
last_update: 23-01-2022 16:37
hidden: true
days_until_collection_date: null
is_collection_date_today: false
icon: mdi:recycle
friendly_name: Afvalinfo GFT
```

it  supposed to show the same info as the pbd sensor:

```
year_month_day_date: '2022-01-28'
last_update: 23-01-2022 16:37
hidden: false
days_until_collection_date: 5
is_collection_date_today: false
icon: mdi:recycle
friendly_name: Afvalinfo PBD
```

afvalinfo.nl shows that next friday both will be collected, but only pbd is updating accordingly.

**Comment by JBakers** [comment] 2022-01-23 15:46
Apologies for creating a similar issue as https://github.com/heyajohnny/afvalinfo/issues/250
Didnt see it as I was searching for gft issues, but that issue same to be related.

**Comment by heyajohnny** [comment] 2022-01-23 20:55
Can you please give me a location (doesn't have to be your location, but a location that has this issue), so I can reproduce the issue. Thnx!

**Comment by tp-ops** [comment] 2022-01-24 19:03
I'm experiencing the same issue. My location is Boekel. Waste management of this municipality has been merged with Land van Cuijk (https://www.gemeentelandvancuijk.nl/afvalkalender/)

**Comment by heyajohnny** [comment] 2022-01-24 20:28
@tp-ops Land van Cuijk is working just fine for Boekel
![image](https://user-images.githubusercontent.com/20553716/150859538-35dd2f9b-fc9b-4b1e-8813-acf32bb742c4.png)

**Comment by heyajohnny** [comment] 2022-01-28 14:19
I've just pushed an update. It should be working with location 'boekel'

**Comment by JBakers** [comment] 2022-01-28 18:13
Yes,  its working again!
Thank you!

**Comment by tp-ops** [comment] 2022-01-29 13:28
Yes, it seems to be working fine now, my compliments and thank you very much for your prompt support.

**Closed** 2022-02-02 08:49 UTC
