### ISSUE TITLE
sensor.afvalinfo_today changed behavior

### ISSUE THREAD

**Issue by DanielNL** [heyajohnny/afvalinfo#223] opened 2021-10-29 14:06 UTC
Hi heyajohnny,

I've been using this integration for a long time now and all of a sudden the sensor.afvalinfo_today changed behaviour. Instead of showing the correct type of trash pickup for the entire day it only shows for 2 hours and then chages state back to 'none'. Any info on this?

![2021-10-29_16-04-24](https://user-images.githubusercontent.com/553060/139449031-4d980b63-9bad-4b1f-9dba-4d946f58cb7f.png)

**Comment by heyajohnny** [comment] 2021-11-08 13:29
That is strange. Maybe the waste collector or your Home Assistant went offline, so the sensor couldn't catch any data and changed the sensor to none. I can't find anything wrong and can't think of anything other...

**Comment by Ronker32** [comment] 2021-11-12 10:44
I don't know which waste collector you're using, but I'm also experiencing this issue with Twente Milieu. It seems that they might have changed something in the provided data. I found this issue with the official integration: https://github.com/home-assistant/core/issues/58882. I don't think it's specifically an issue with this custom component, but more an issue of the changed provided data from the waste collector.

**Comment by heyajohnny** [comment] 2021-11-13 20:49
Sorry... I can't reproduce it. Maybe if you have some concrete example with a 'postcode' , 'streetnumber' I might be able to reproduce it.

**Comment by Ronker32** [comment] 2021-11-15 09:37
For example, this is happening to postcode 7574 CA, streetnumber 35.

**Comment by heyajohnny** [comment] 2021-11-26 08:25
Sorry for the wait... I've dugged a bit deeper in this issue and found out that it's a bug at the 'Twente Milieu' waste collector.
I used your example location and have the same problem:
![image](https://user-images.githubusercontent.com/20553716/143548902-e73a679b-1eea-4e09-a9a4-df3bd2419b87.png)
When I look at the data from 'Twente Milieu', I see that the GFT for today is already gone:
![image](https://user-images.githubusercontent.com/20553716/143549166-d30137eb-ee9a-4f28-a0e7-cd18fa0a0faf.png)
The date is also gone in the API data:
![image](https://user-images.githubusercontent.com/20553716/143549997-a2849c3d-ad34-4170-94e1-7b0cfa192eab.png)

There's not much I can do about it. You can contact 'Twente Milieu' with your issue and they might fix it...

**Comment by DanielNL** [comment] 2021-11-26 08:39
Hi guys,

thank you both for following up on this issue. I have sent a request to 'Twente Milieu' just now, I will post here if i hear anything.

Cheers.

**Comment by heyajohnny** [comment] 2022-01-18 17:19
I'll close the issue, because I assume it's fixed by now

**Closed by heyajohnny** 2022-01-18 17:19 UTC
