### ISSUE TITLE
Only 1 of 2 "afval" showing today.

### ISSUE THREAD

**Issue by JBakers** [heyajohnny/afvalinfo#378] opened 2023-05-05 07:23 UTC
On [4fv4l](https://4fv4l.nl/) it shows both PBD and GFT for our address today.
But the HA integration only shows PBD.

The GFT shows "unknown".

GFT attributes:
`error: true
friendly_name: gft
year_month_day_date: null
last_update: 05-05-2023 09:13
hidden: false
days_until_collection_date: null
is_collection_date_today: false
last_collection_date: null
total_collections_this_year: null
whole_year_dates: null
icon: mdi:recycle`

PBD attributes:
`error: false
friendly_name: pbd
year_month_day_date: '2023-05-05'
last_update: 05-05-2023 09:13
hidden: false
days_until_collection_date: 0
is_collection_date_today: true
last_collection_date: null
total_collections_this_year: null
whole_year_dates: null
icon: mdi:recycle`

Restafval is also showing an error (but is not scheduled today)
`error: true
friendly_name: restafval
year_month_day_date: null
last_update: 05-05-2023 09:13
hidden: false
days_until_collection_date: null
is_collection_date_today: false
last_collection_date: null
total_collections_this_year: null
whole_year_dates: null
icon: mdi:recycle`

I have no errors in my log regarding afvalinfo.

**Comment by AarvdH** [comment] 2023-05-05 10:11
Hello, Having a similar problem since update this morning to 2023.5
GFT is working
Paper is Unknown
error: true friendly_name: kerstboom year_month_day_date: null last_update: 05-05-2023 10:03 hidden: false days_until_collection_date: null is_collection_date_today: false last_collection_date: null total_collections_this_year: null whole_year_dates: null icon: mdi:recycle
--
Plastic is Unknown
error: true
friendly_name: Plastic
year_month_day_date: null
last_update: 05-05-2023 10:03
hidden: false
days_until_collection_date: null
is_collection_date_today: false
last_collection_date: null
total_collections_this_year: null
whole_year_dates: null
icon: mdi:bottle-soda-classic
entity_picture: /local/images/pmd-icon.png

Reloaded the integration but did not help.
No further errors

**Comment by Laho19** [comment] 2023-05-05 20:02
Same here, looks like the API or integration has some date/time issues;

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 665, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 546, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: as_timestamp got invalid input 'unknown' when rendering template '{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%d-%m-%Y') }}' but no default was specified
2023-05-05 21:22:16.602 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: as_timestamp got invalid input 'unknown' when rendering template '{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%d-%m-%Y') }}' but no default was specified') while processing template 'Template<template=({{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%d-%m-%Y') }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.datum'

**Comment by heyajohnny** [comment] 2023-05-06 10:58
I'll look into it in acouple of hours. I'll let you know if I can pinpoint the issue

**Comment by heyajohnny** [comment] 2023-05-06 19:24
I just made a new version and removed 'timespanindays'. I also did an extra check on a possible empty array, which gave an error in my test environment. Please let me know if everything works as expected again, after this update

**Comment by Laho19** [comment] 2023-05-07 06:32
Seems like GFT sensor is working and others aren't for me;

Attributes
Error
true
Year month day date
Unknown
Last update
07-05-2023 08:29
Days until collection date
Unknown
Is collection date today
false
Last collection date
Unknown
Total collections this year
Unknown
Whole year dates
Unknown

**Comment by heyajohnny** [comment] 2023-05-07 07:32
@Laho19 are you sure that you have the new version (v1.1.1)? Can you give me your postcode? (Housenumber not needed) maybe I can reproduce the problem then. Do you see any errors in your log?

**Comment by Laho19** [comment] 2023-05-07 07:54
> @Laho19 are you sure that you have the new version (v1.1.1)? Can you give me your postcode? (Housenumber not needed) maybe I can reproduce the problem then. Do you see any errors in your log?

Yes I do. 7609EB. No errors related to afvalinfo.

**Comment by JBakers** [comment] 2023-05-07 07:56
For me, the update has fixed it.
All three I'm using, GFT, PBD en Restafval are working again.

**Comment by jngl61** [comment] 2023-05-07 09:06
> ing the timespanindays from the config and reboot, the GFT sensor is working and others aren't for

Same problem. 
only GFT works fine. 
using 1.1.1
postcode 5246AP

**Comment by robertjan** [comment] 2023-05-07 09:13
Same issue, Only the sensor.afvalinfo_gft working fine and is showing a datestamp

- sensor.afvalinfo_papier = status unknown
error: true
friendly_name: Papier
year_month_day_date: null
last_update: 07-05-2023 11:06
days_until_collection_date: null
is_collection_date_today: false
last_collection_date: null
total_collections_this_year: null
whole_year_dates: null
icon: mdi:recycle
entity_picture: /local/images/papier-icon.png

- sensor.afvalinfo_pbd = status unknown
error: true
friendly_name: Pbd
year_month_day_date: null
last_update: 07-05-2023 11:06
days_until_collection_date: null
is_collection_date_today: false
last_collection_date: null
total_collections_this_year: null
whole_year_dates: null
icon: mdi:recycle

This issues starts after the update to 2023.5.*

Afval Info is up-to-date
postcode: 7334BL

i did try to replace my sensor config with the one that`s created from https://4fv4l.nl/ha but still the same issue.

**Comment by heyajohnny** [comment] 2023-05-07 09:18
Yeah, only the first sensor under resources is updating, but I don't know why... Home Assistant must've changed something in the update process after their last release, but I can't find anything yet in their update [blog:](https://developers.home-assistant.io/blog/)

**Comment by jngl61** [comment] 2023-05-07 11:28
> Yeah, only the first sensor under resources is updating, but I don't know why... Home Assistant must've changed something in the update process after their last release, but I can't find anything yet in their update [blog:](https://developers.home-assistant.io/blog/)

No idea why, but restafval, papier and gft works here again. Nothing changed and did not reboot.

**Comment by bafplus** [comment] 2023-05-07 11:32
I have this gut feeling that the first update run after the update only fills in the gft data and skips/errors the others. Then on the next updat ecycle it fetches all data correctly.

Is thare a way to force this "daily" refresh to test this?

**Comment by bafplus** [comment] 2023-05-07 18:20
confirmed all data is pulled after a few hours!
So if you have just 1 (probably gft) with a date, just wait a few hours and the rest of the data will be pulled in.

**Comment by heyajohnny** [comment] 2023-05-07 19:17
Probably in one of the newer HA versions something in the timing of the 'init' and/or 'update' method has been changed, which caused all sensors to be cycled before all data was received. Now I have modified the code so that it retrieves the data sooner. Everything should work as before with the new version (1.1.3)

**Comment by Rocker20** [comment] 2023-05-07 20:16
FYI: since the last update 1.1.3 I have the data from December 2023. Better than no data but it is not yet what it should be. Hopefully this will resolve itself as I won't be able to make any adjustments for the next few days.

**Comment by heyajohnny** [comment] 2023-05-07 20:36
@Rocker20 Can you explain?

**Comment by Laho19** [comment] 2023-05-07 20:38
> Probably in one of the newer HA versions something in the timing of the 'init' and/or 'update' method has been changed, which caused all sensors to be cycled before all data was received. Now I have modified the code so that it retrieves the data sooner. Everything should work as before with the new version (1.1.3)

Up and running again. Thnx.

**Comment by Rocker20** [comment] 2023-05-07 20:39
> > Probably in one of the newer HA versions something in the timing of the 'init' and/or 'update' method has been changed, which caused all sensors to be cycled before all data was received. Now I have modified the code so that it retrieves the data sooner. Everything should work as before with the new version (1.1.3)
> 
> Up and running again. Thnx.

Sure 
![image](https://user-images.githubusercontent.com/55502858/236701562-13f4d3c8-5ae4-488b-ae4a-a436da2d7c51.png)

**Comment by Rocker20** [comment] 2023-05-07 20:40
> @Rocker20 Can you explain?

sure 
![image](https://user-images.githubusercontent.com/55502858/236701587-6392352a-c80c-4cc9-84a5-b53f010538cc.png)

**Comment by heyajohnny** [comment] 2023-05-07 21:36
@Rocker20 What's your postcode? Maybe I can reproduce it

**Comment by Rocker20** [comment] 2023-05-07 21:41
> @Rocker20 What's your postcode? Maybe I can reproduce it

7609ee

**Comment by heyajohnny** [comment] 2023-05-09 21:09
@Rocker20 I just made a new release. The issue should be fixed. Please let me know if everything works as expected

**Comment by Rocker20** [comment] 2023-05-09 22:04
> @Rocker20 I just made a new release. The issue should be fixed. Please let me know if everything works as expected

the data looks fine again after the update and restart from Home Assistant, but I have to adjust a few things when I'm back from vacation. Thanks for the effort!

**Comment by heyajohnny** [comment] 2023-05-09 22:07
I think everything is fixed for this issue. I'm closing it

**Closed by heyajohnny** 2023-05-09 22:07 UTC

**Comment by Rocker20** [comment] 2023-05-09 22:08
> I think everything is fixed for this issue. I'm closing it

Fine by me! Thanks! 🎉
