### ISSUE TITLE
Whole year attribute not showing

### ISSUE THREAD

**Issue by xtrmenl** [heyajohnny/afvalinfo#408] opened 2023-12-13 11:24 UTC
I the v1 version the whole year tag included the upcoming pickups in the attributes of the sensor

Currently says unknown
Would like to integrate with the calender again, like with v1

**Comment by heyajohnny** [comment] 2023-12-13 20:52
Should be fixed in v2.0.5. Please let me know if it works

**Comment by Rocker20** [comment] 2023-12-13 21:02
Just updated to 2.0.5

last_update: 13-12-2023 22:01
days_until_collection_date: 8
is_collection_date_today: false
last_collection_date: null
total_collections_this_year: null
whole_year_dates: null

**Comment by heyajohnny** [comment] 2023-12-13 21:20
@Rocker20 did you check 'Get data for the whole year' checkbox when you added the sensors?
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/6d469450-5c6d-4e37-a52d-d3961badb18d)

**Comment by Rocker20** [comment] 2023-12-13 21:22
Yes i did

**Comment by heyajohnny** [comment] 2023-12-13 21:29
I've just updated afvalinfo in my living room HA and looks like it's working fine:
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/54ce870d-8605-41ab-a850-d5de91ddf289)
Also @Rocker20 confirmed it. I'm closing this issue

**Closed by heyajohnny** 2023-12-13 21:29 UTC

**Comment by xtrmenl** [comment] 2023-12-13 23:46
Worked without te-adding update and restart did the job. Thank you
