### ISSUE TITLE
HASS Core version after 2024.06 reports blocking calls to format_date() function

### ISSUE THREAD

**Issue by altserg** [heyajohnny/afvalinfo#449] opened 2024-07-31 13:06 UTC
It's probably already known, but I'm logging this issue to keep track of resolution:

2024-07-31 03:34:39.243 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/local/hass/instance-1/lib/python3.12/site-packages/babel/global.dat', 'rb') inside the event loop by custom integration 'afvalinfo' at custom_components/afvalinfo/sensor.py, line 369: locale_date = format_date( (offender: /usr/local/hass/instance-1/lib/python3.12/site-packages/babel/core.py, line 75: with open(filename, 'rb') as fileobj:), please create a bug report at https://github.com/heyajohnny/afvalinfo/issues
  File "/home/hass/.homeassistant/custom_components/afvalinfo/sensor.py", line 369, in async_update
2024-07-31 03:34:39.283 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/local/hass/instance-1/lib/python3.12/site-packages/babel/locale-data/root.dat', 'rb') inside the event loop by custom integration 'afvalinfo' at custom_components/afvalinfo/sensor.py, line 369: locale_date = format_date( (offender: /usr/local/hass/instance-1/lib/python3.12/site-packages/babel/localedata.py, line 123: with open(filename, 'rb') as fileobj:), please create a bug report at https://github.com/heyajohnny/afvalinfo/issues
  File "/home/hass/.homeassistant/custom_components/afvalinfo/sensor.py", line 369, in async_update

**Comment by PuckStar** [comment] 2024-09-08 15:26
I have the same issue (version 2.3.1)

`2024-09-08 17:21:13.261 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/babel/global.dat', 'rb') inside the event loop by custom integration 'afvalinfo' at custom_components/afvalinfo/sensor.py, line 369: locale_date = format_date( (offender: /usr/local/lib/python3.12/site-packages/babel/core.py, line 75: with open(filename, 'rb') as fileobj:), please create a bug report at https://github.com/heyajohnny/afvalinfo/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 678, in _async_handle_interval_callback
    self.config_entry.async_create_background_task(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1182, in async_create_background_task
    task = hass.async_create_background_task(target, name, eager_start)
  File "/usr/src/homeassistant/homeassistant/core.py", line 862, in async_create_background_task
    task = create_eager_task(target, name=name, loop=self.loop)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1052, in _async_update_entity_states
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/afvalinfo/sensor.py", line 369, in async_update
    locale_date = format_date(

2024-09-08 17:21:13.292 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/babel/locale-data/root.dat', 'rb') inside the event loop by custom integration 'afvalinfo' at custom_components/afvalinfo/sensor.py, line 369: locale_date = format_date( (offender: /usr/local/lib/python3.12/site-packages/babel/localedata.py, line 123: with open(filename, 'rb') as fileobj:), please create a bug report at https://github.com/heyajohnny/afvalinfo/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 678, in _async_handle_interval_callback
    self.config_entry.async_create_background_task(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1182, in async_create_background_task
    task = hass.async_create_background_task(target, name, eager_start)
  File "/usr/src/homeassistant/homeassistant/core.py", line 862, in async_create_background_task
    task = create_eager_task(target, name=name, loop=self.loop)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1052, in _async_update_entity_states
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/afvalinfo/sensor.py", line 369, in async_update
    locale_date = format_date(`

**Comment by heyajohnny** [comment] 2024-09-10 20:36
@PuckStar Does this also happen after a reboot? This should not happen if you've got the latest version of afvalinfo

**Comment by altserg** [comment] 2024-09-11 08:30
I confirm the issue is present after update to HASS Core 2024.9.1 and restart.

**Comment by heyajohnny** [comment] 2024-09-11 10:40
I'll keep the issue open, but it's not reproducable by me
![image](https://github.com/user-attachments/assets/62029b6d-e9d1-4ac5-8d70-d78d0fd51623)
It looks like something is being cached on your side that keeps some of the old code for afvalinfo

**Comment by heyajohnny** [comment] 2024-09-13 19:35
I reproduced it... It indeed had something to do with the date (your custom date format).
It should be fixed in v2.1.4. Please let me know if the newest version fixes this issue

**Comment by PuckStar** [comment] 2024-09-14 16:17
> I reproduced it... It indeed had something to do with the date (your custom date format). It should be fixed in v2.1.4. Please let me know if the newest version fixes this issue

Yes it's fixed for me now.  Thanks!

**Comment by heyajohnny** [comment] 2024-09-15 12:29
Then it's probably fixed. I'm closing the issue

**Closed by heyajohnny** 2024-09-15 12:29 UTC

**Comment by altserg** [comment] 2024-09-18 13:04
I confirm that the issue is also gone with latest update in HASS Core 2024.9.2
